SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `estudiantes`.`articles` CHANGE COLUMN `title` `title` VARCHAR(150) NOT NULL  ;

ALTER TABLE `estudiantes`.`cursos` CHANGE COLUMN `name` `name` VARCHAR(150) NOT NULL  ;

ALTER TABLE `estudiantes`.`events` CHANGE COLUMN `name` `name` VARCHAR(150) NOT NULL  ;

ALTER TABLE `estudiantes`.`enterprises` CHANGE COLUMN `enterprise` `enterprise` VARCHAR(150) NOT NULL  ;

ALTER TABLE `estudiantes`.`emprendedores` CHANGE COLUMN `title` `title` VARCHAR(150) NOT NULL  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
